#!/bin/bash

load inquirer

check() {
  if [ ! -f $SERVICE_CONFIG ]; then
     touch $SERVICE_CONFIG
  fi

  config::load_file $SERVICE_CONFIG

  if [ -z "$SERVICE_REMOTEDEV_COMPANY" ]; then
    inquirer::text "请输入 SERVICE_REMOTEDEV_COMPANY:" value
    config::set SERVICE_REMOTEDEV_COMPANY $value $SERVICE_CONFIG
  fi

  if [ -z "$SERVICE_REMOTEDEV_SOURCE_CODE_DIR" ]; then
    inquirer::text "请输入 SERVICE_REMOTEDEV_SOURCE_CODE_DIR:" value
    config::set SERVICE_REMOTEDEV_SOURCE_CODE_DIR $value $SERVICE_CONFIG
  fi

  if [ -z "$SERVICE_REMOTEDEV_GIT_USER" ]; then
    inquirer::text "请输入 SERVICE_REMOTEDEV_GIT_USER:" value
    config::set SERVICE_REMOTEDEV_GIT_USER $value $SERVICE_CONFIG
  fi

  if [ -z "$SERVICE_REMOTEDEV_GIT_EMAIL" ]; then
    inquirer::text "请输入 SERVICE_REMOTEDEV_GIT_EMAIL:" value
    config::set SERVICE_REMOTEDEV_GIT_EMAIL $value $SERVICE_CONFIG
  fi

  if [ -z "$SERVICE_REMOTEDEV_SSH_PORT" ]; then
    inquirer::text "请输入 SERVICE_REMOTEDEV_SSH_PORT:" value
    config::set SERVICE_REMOTEDEV_SSH_PORT $value $SERVICE_CONFIG
  fi

  if [ -z "$SERVICE_REMOTEDEV_PREVILEGED" ]; then
    local choices=(
      "Yes"
      "No"
    )
    inquirer::select "Allow root previledge ?" choices value
    if [ "$value" = "Yes" ]; then
      config::set SERVICE_REMOTEDEV_PREVILEGED true $SERVICE_CONFIG
    else
      config::set SERVICE_REMOTEDEV_PREVILEGED false $SERVICE_CONFIG
    fi
  fi

  # ensure load
  config::load_file $SERVICE_CONFIG

  #@TODO
  export SERVICE_REMOTEDEV_COMPANY=$SERVICE_REMOTEDEV_COMPANY
  export SERVICE_REMOTEDEV_INLETS_CLIENT_ID=$SERVICE_REMOTEDEV_INLETS_CLIENT_ID
  export SERVICE_REMOTEDEV_INLETS_CLIENT_SECRET=$SERVICE_REMOTEDEV_INLETS_CLIENT_SECRET
  export SERVICE_REMOTEDEV_INLETS_PORT=$SERVICE_REMOTEDEV_INLETS_PORT
  export SERVICE_REMOTEDEV_SOURCE_CODE_DIR=$SERVICE_REMOTEDEV_SOURCE_CODE_DIR
  export SERVICE_REMOTEDEV_GIT_USER=$SERVICE_REMOTEDEV_GIT_USER
  export SERVICE_REMOTEDEV_GIT_EMAIL=$SERVICE_REMOTEDEV_GIT_EMAIL
  export SERVICE_REMOTEDEV_SSH_PORT=$SERVICE_REMOTEDEV_SSH_PORT
  export SERVICE_REMOTEDEV_PREVILEGED=$SERVICE_REMOTEDEV_PREVILEGED

  # USER / GROUP
  export SERVICE_REMOTEDEV_USER_ID=$(id -u)
  export SERVICE_REMOTEDEV_GROUP_ID=$(id -g)
  # Docker
  export SERVICE_REMOTEDEV_DOCKER_SOCK=/var/run/docker.sock
  # @TODO placeholder
  export SERVICE_REMOTEDEV_DOCKER_CLI=/bin/bash
  which docker >> /dev/null 2>&1
  if [ $? -eq 0 ]; then
    export SERVICE_REMOTEDEV_DOCKER_CLI=$(which docker)
  fi
}

check $@
