version: '3.7'

services:
  workspace:
    restart: always
    build:
      context: ./image
    ports:
      - 0.0.0.0:${SERVICE_REMOTEDEV_SSH_PORT}:22
    hostname: ${SERVICE_REMOTEDEV_COMPANY}
    #user: ${SERVICE_REMOTEDEV_USER_ID}:${SERVICE_REMOTEDEV_GROUP_ID}
    privileged: '${SERVICE_REMOTEDEV_PREVILEGED:-false}'
    environment:
      GIT_USER: ${SERVICE_REMOTEDEV_GIT_USER}
      GIT_EMAIL: ${SERVICE_REMOTEDEV_GIT_EMAIL}
    volumes:
      - ${SERVICE_DATA}/.vscode-server:/home/workspace/.vscode-server
      - ${SERVICE_DATA}/.ssh:/home/workspace/.ssh
      - ${SERVICE_REMOTEDEV_SOURCE_CODE_DIR}:/home/workspace/code
      - ${SERVICE_REMOTEDEV_DOCKER_CLI}:/usr/bin/docker
      - ${SERVICE_REMOTEDEV_DOCKER_SOCK}:/var/run/docker.sock

networks:
  default:
    external: true
    name: compose-ingress
