version: '3.7'

services:
  workspace:
    restart: always
    image: whatwewant/workspace:${SERVICE_WORKSPACE_IMAGE_VERSION}
    ports:
      - 0.0.0.0:${SERVICE_REMOTEDEV_SSH_PORT}:22
    hostname: ${SERVICE_REMOTEDEV_COMPANY}
    #user: ${SERVICE_REMOTEDEV_USER_ID}:${SERVICE_REMOTEDEV_GROUP_ID}
    privileged: '${SERVICE_REMOTEDEV_PREVILEGED:-true}'
    environment:
      GIT_USER: ${SERVICE_REMOTEDEV_GIT_USER}
      GIT_EMAIL: ${SERVICE_REMOTEDEV_GIT_EMAIL}
    volumes:
      - ${SERVICE_DATA}/.vscode-server:/home/workspace/.vscode-server
      - ${SERVICE_DATA}/.ssh:/home/workspace/.ssh
      - ${SERVICE_DATA}/.gpm:/home/workspace/.gpm
      - ${SERVICE_REMOTEDEV_SOURCE_CODE_DIR}:/home/workspace/code
      - ${SERVICE_DATA}/zmicro/data:/data
      - ${SERVICE_DATA}/zmicro/configs:/configs
      # - ${SERVICE_REMOTEDEV_DOCKER_CLI}:/usr/bin/docker
      # - ${SERVICE_REMOTEDEV_DOCKER_SOCK}:/var/run/docker.sock
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

networks:
  default:
    external: true
    name: compose-ingress
